### ISSUE TITLE
A question about extra query params

### ISSUE THREAD

**Issue by sajov** [feathersjs-ecosystem/feathers-elasticsearch#28]
because of working on a feathers-solr adapter i reviewed your code and have learned :-)
But why add params like $phrase instead of using $search and let user escape the string
or let them add asterisk as prefix or suffix search?

thx

**Comment by jciolek** [comment]
Hi @sajov,

Thanks for your kind words. I am afraid I did not grasp the problem. Could you give some examples?

Cheers,
Jacek

**Comment by sajov** [comment]
Hi @jciolek,

i do not know query in elasticsearch
here is how i do it in [feathers-solr](https://github.com/sajov/feathers-solr#search)

thanks
