### ISSUE TITLE
Add ability to define entire query manually

### ISSUE THREAD

**Issue by DesignByOnyx** [feathersjs-ecosystem/feathers-elasticsearch#47]
It would be nice to have some sort of mechanism to allow consumers to pass in a full query object. This would allow users to have full control over search queries and provide an escape hatch for those situations where a complex query is needed. Here are some suggestions to start the conversation:

1. A special `$bool` or `$query` property which signifies the the user has built a query themselves.

    ```js
    {
      $bool: { must: { match: 'query' } }
    }
    ```
2. Allow `params.elasticsearch` to hold data which is merged onto the object passed to the underlying ES client. This would be the "top level" object passed to the ES client:

   ```js
    (context) => {
      context.params.elasticsearch = { waitForActiveShards: '2' };
    }
    ```

The feathers-sequelize and feathers-knex adapters (and I'm sure others) allow users to set `params[adapter-name]` which is merged with the options generated by the adapter. This gives users 100% control of the options passed to the underlying sequelize/knex client.

**Comment by jciolek** [comment]
Hey @DesignByOnyx,

I really like the second idea. In fact it's been on my to-do list for a while :)

With regards to the first one, I'm not quite sure. Elasticsearch lets the user create very heavy queries, which can bring the system down to its knees. That could provide an easy way to DOS the ES cluster for potential attacker. To sweeten it up a bit, we currently have `raw` method on the service, which should take care of that use case, if you wanted to have some complex queries. I hope it makes sense?

**Comment by jljorgenson18** [comment]
I think the second option that @DesignByOnyx suggested would be the best of the both worlds. Using "raw" removes a lot of the goodies we get with the cross adapter queries and standard feathers service apis. It seems like checking params.elasticsearch before each function call would be fairly straightforward.
