### ISSUE TITLE
Issue with .create

### ISSUE THREAD

**Issue by boboci9** [feathersjs-ecosystem/feathers-elasticsearch#60]
Hi, first let me tell you great package, congrats to the authors.

I have read your docs multiple times but I can't find enough examples about the join setup.
I am not sure how you set up the services `postService` and `commentService`.
I am trying to create a child-parent join structure and then I am trying to add items just like your example:
I have a mainservice and I can make a find query but sadly I can't make a create one.
```
const mainService = service({
    Model: new elasticsearch.Client({
        host: 'localhost:9200',
        apiVersion: '6.0'
    }),
    paginate: {
        default: 10,
        max: 50
    },
    elasticsearch: {
        index: 'find',
    },
    esVersion: '6.0'
    });
   mainService
        .find({
            query: {
                $all: true
            }
        }) //this works fine
Result: 
```
{"total":2,"skip":0,"limit":10,"data":[{"_meta":{"_index":"find","_type":"_doc","_id":"c9552b9b-1152-4d3b-b6f6-b9a0eb22f285","_score":1},"type":"item","uuid":"c9552b9b-1152-4d3b-b6f6-b9a0eb22f285","title":"Test title","softTitle":"Test title","snippet":"Snippet string","thumbnailURL":"http://image.com/1","content":"Content String","author":"Jon Doe","siteName":"http://example.com","description":"Description string","find_join_field":"item","_id":"c9552b9b-1152-4d3b-b6f6-b9a0eb22f285"},{"_meta":{"_index":"find","_type":"_doc","_id":"c9552b9b-1152-4d3b-b6f6-b9a0eb22f296","_score":1,"_routing":"1"},"type":"map","uuid":"c9552b9b-1152-4d3b-b6f6-b9a0eb22f296","name":"Map name","find_join_field":{"name":"map","parent":"c9552b9b-1152-4d3b-b6f6-b9a0eb22f285"},"_id":"c9552b9b-1152-4d3b-b6f6-b9a0eb22f296"}]}
```
const itemService = service({
        Model: new elasticsearch.Client({
            host: 'localhost:9200'
        }),
        paginate: {
            default: 10,
            max: 50
        },
        elasticsearch: {
            index: 'find',
            type: '_doc'
        },
        esVersion: '6.4',
        parent: 'parent',
        routing: 'routing',
        join: 'mapitem',
        meta: 'meta'
        })
itemService..create({
            "_id": "222",
                "type":"item",
                "uuid":"222",
                "title":"Test title",
                "softTitle":"Test title",
                "snippet":"Snippet string",
                "thumbnailURL":"http://image.com/1",
                "content": "Content String",
                "author" :"Jon Doe",
                "siteName":"http://example.com",
                "description":"Description string",
                "mapitem":"item"
        })
// this gives the following error
```
`Cannot read property 'query' of undefined
    at createCore (/home/bogi/Work/Find/findES/node_modules/feathers-elasticsearch/lib/core/create/core.js:17:16)`

What am I missing from the itemService declaration to make it work with joins?

Thank you for your help in advance.

**Comment by jciolek** [comment]
Hey @boboci9,

Thanks for using the package! I've gone through your code example, but the definition of the `itemService` seems to be missing. Could you provide a complete example, preferable along with an excerpt from Elasticsearch mapping type?

Thanks,
Jacek

**Comment by boboci9** [comment]
Hi @jciolek,
Not sure what is the reason for the error but I managed to fix it with a second empty object parameter, so id I do `itemService..create(doc, {}) ` i don't have the error anymore.
Now the issue is  I manage to insert only parent types, not sure you to insert a child.
I am trying with the following parameters:
```
parent = {
  "_id": "11",
  name: "I am the parent"
 };
  itemService.create(
        parent,{}
    );
parentId = "11";
doc = {
        name:"Insert test child",
        _id: id,
        _parent: parentId,
        routing: parentId,
        aka: 'mapitem',
        meta: { _id: parentId 
        }
      };
    itemService.create(
        doc,{}
    );
```
The issue is both items are inserted as parents, the child link is not created. Can you tell me how to set up the service to insert a child?

**Comment by boboci9** [comment]
I edited, with this final solution I managed to create a child item.
