### ISSUE TITLE
I could also use upsert support

### ISSUE THREAD

**Issue by penngrove** [feathersjs-ecosystem/feathers-elasticsearch#65]
upsert does not appear to be implemented, but it would be nice if the create and/or update had an upsert option. I see a reference in the code as a TODO and was wondering if this is coming, I can volunteer to implement this if you are interested.

**Comment by daffl** [comment]
Submitting a pull request would definitely be the quickest and best way to get this feature in 😄

**Comment by penngrove** [comment]
First log the issue, then submit the PR :-)

**Comment by daffl** [comment]
Indeed. Just saw the other PR, thank you for doing that!

**Comment by penngrove** [comment]
You should get a PR for this one over the weekend, I am planning an _upsert_ parameter for the _create_ and _update_ method (defaulting to false, i.e. current behavior)

**Comment by penngrove** [comment]
PR #66 submitted

**Comment by daffl** [comment]
Closed via #66
